sudo: required

language: node_js
node_js:
  - "stable"

services:
  - docker

before_install:
  - docker build -t abhayk26/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abhayk26/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-env"
  env: "Dockerreactenv-env"
  bucket_name: "elasticbeanstalk-us-east-1-329852076361"
  bucket_path: "docker-react-env"
  on:
    branch: master
