sudo: required

language: node_js
node_js:
  - "stable"

services:
  - docker

before_install:
  - docker build -t abhayk26/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abhayk26/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-env"
  env: "Dockerreactenv-env"
  bucket_name: "docker-react-env-s3bucket"
  bucket_path: "EBApptest"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"